config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :order, only: [:index, :update]

  resources :carts, only: [:show]

  resources :order_items, only: [:create, :update, :destroy]

  get '/order/items', to: 'order#items', as: 'all_items'

  get '/admin', to: 'admin#index', as: 'admin_index'

  get '/admin/new', to: 'admin#new', as: 'admin_new'

  get '/admin/products', to: 'admin#products', as: 'admin_products'

  get '/admin/new_product', to: 'admin#new_product', as: 'admin_new_product'

  patch '/admin/update_special/:id', to: 'admin#update_special', as: 'admin_update_special'

  patch '/admin/update_inventory/:id', to: 'admin#update_inventory', as: 'admin_update_inventory'

  delete '/admin/delete_special/:id', to: 'admin#delete_special', as: 'admin_delete_special'

  delete '/admin/delete_inventory/:id', to: 'admin#delete_inventory', as: 'admin_delete_inventory'

  post '/admin/create', to: 'admin#create_product', as: 'admin_create_product'

  post '/admin/create_inventory', to: 'admin#create_inventory_product', as: 'admin_create_inventory_product'

  post '/admin/create_special', to: 'admin#create_special_product', as: 'admin_create_special_product'

  post 'create_user' => 'admin#create', as: :create_user

  post 'selected_user' => 'admin#selected_user', as: :selected_user

  post 'create_product_user' => 'admin#product_user', as: :product_user

  delete 'delete_product_user' => 'admin#delete_product', as: :delete_product

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
end

app/views/admin/_addedproducts.html.erb
<%= bootstrap_form_for @user_product, method: 'delete', url: delete_product_path do |f| %>
  <div id="special-products-table">
    <table class="table">
    <% @selected_user.special_products.each do |special_product| %>
      <tr>
        <th><%= special_product.description %></th>
        <th>
          <th><%= f.check_box :special_product_id, {:multiple => true, class: "added-product-checkbox"}, checked_value = "#{special_product.id}", unchecked_value = nil%></th>
        </th>
        <th>
          <%= f.submit "Delete Product", class: "btn btn-primary" %>
        </th>
      </tr>
    <% end %>
    <% @selected_user.inventory_products.each do |inventory_product| %>
      <tr>
        <th><%= inventory_product.description %></th>
        <th>
          <th><%= f.check_box :inventory_product_id, {:multiple => true, class: "added-product-checkbox"}, checked_value = "#{inventory_product.id}", unchecked_value = nil%></th>
        </th>
        <th>
          <%= f.submit "Delete Product", class: "btn btn-primary" %>
        </th>
      </tr>
    <% end %>
    </table>
  </div>
<% end %>

app/views/admin/_all-products.html.erb
<div id="special-products-table">
  <table class="table">
  <% @special_products.each do |special_product| %>
    <tr>
      <th><%= special_product.description %></th>
      <th><%= special_product.inventory_code %></th>
      <th><%= special_product.product_code %></th>
      <th><button type="button" name="button" class="btn btn-primary edit-product-special" value="<%= special_product.id %>">Edit</button></th>
      <th><button type="button" name="button" class="btn btn-primary delete-product-special" value="<%= special_product.id %>">Delete</button></th>
    </tr>
    <tr class="edit-tr" id="<%= special_product.inventory_code %>">
      <%= bootstrap_form_for special_product, method: 'patch', url: delete_product_path do |f| %>
        <th>
          <%= f.text_field :description, value: special_product.description %>
        </th>
        <th>
          <%= f.text_field :inventory_code, value: special_product.inventory_code %>
        </th>
        <th>
          <%= f.text_field :product_code, value: special_product.product_code %>
        </th>
        <th>
          <%= f.submit :class => "btn btn-primary edit-button-submit-special", :id => "#{special_product.id}" %>
        </th>
        <th>
          <button type="button" name="button" class="btn btn-primary get-out-of-edit">Leave Edit</button>
        </th>
      <% end %>
    </tr>
  <% end %>
  </table>
</div>
<div id="inventory-products-table">
  <table class="table">
  <% @inventory_products.each do |inventory_product| %>
  <tr>
    <th><%= inventory_product.description %></th>
    <th><%= inventory_product.inventory_code %></th>
    <th><%= inventory_product.product_code %></th>
    <th><button type="button" name="button" class="btn btn-primary edit-product-special" value="<%= inventory_product.id %>">Edit</button></th>
    <th><button type="button" name="button" class="btn btn-primary delete-product-inventory" value="<%= inventory_product.id %>">Delete</button></th>
  </tr>
  <tr class="edit-tr" id="<%= inventory_product.inventory_code %>">
    <%= bootstrap_form_for inventory_product, method: 'patch', url: delete_product_path do |f| %>
      <th>
        <%= f.text_field :description, value: inventory_product.description %>
      </th>
      <th>
        <%= f.text_field :inventory_code, value: inventory_product.inventory_code %>
      </th>
      <th>
        <%= f.text_field :product_code, value: inventory_product.product_code %>
      </th>
      <th>
        <%= f.submit :class => "btn btn-primary edit-button-submit-inventory", :id => "#{inventory_product.id}" %>
      </th>
      <th>
        <button type="button" name="button" class="btn btn-primary get-out-of-edit">Leave Edit</button>
      </th>
    <% end %>
  </tr>
  <% end %>
  </table>
</div>

app/views/admin/_special.html.erb
<%= bootstrap_form_for @user_product, url: product_user_path do |f| %>
  <div id="special-products-table">
    <table class="table">
    <% @special_products.each do |special_product| %>
      <tr>
        <th><%= special_product.description %></th>
        <th><%= f.check_box :special_product_id, {:multiple => true, class: "special-product-checkbox"}, checked_value = "#{special_product.id}", unchecked_value = nil%></th>
      </tr>
    <% end %>
    </table>
  </div>
  <div id="inventory-products-table">
    <table class="table">
    <% @inventory_products.each do |inventory_product| %>
      <tr>
        <th><%= inventory_product.description %></th>
        <th><%= f.check_box :inventory_product_id, {:multiple => true, class: "special-product-checkbox"}, checked_value = "#{inventory_product.id}", unchecked_value = nil%></th>
      </tr>
    <% end %>
    </table>
  </div>
  <%= f.submit %>
<% end %>

app/views/admin/_users.html.erb
<table class="table">
  <%= bootstrap_form_for @user_product, url: selected_user_url do |f| %>
    <% @users.each do |user| %>
      <tr>
        <th>
          <%= user.email %>
        </th>
        <th><%= f.radio_button :user_id, user.id %></th>
      </tr>
    <% end %>
    <%= f.submit "Select User", class: "btn btn-primary" %>
  <% end %>
</table>

app/views/admin/index.html.erb
<div id="wrapper">
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand"><%= link_to('Admin', admin_index_path) %></li>
      <li><%= link_to('Manage Users', admin_new_path) %></li>
      <li><%= link_to('Manage Products', admin_products_path) %></li>
      <li><%= link_to('Add Product', admin_new_product_path) %></li>
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    </ul>
  </div>
  <div id="page-content-wrapper" class="admin-home">
    <div class="flex-container">
      <div class="form-row-admin">
        <h1 class="admin-form-title">Create User</h1>
        <%= bootstrap_form_for @user, url: create_user_path do |f| %>
          <%= f.email_field :email, placeholder: "Enter Clients email", label_class: "home-label" %>
          <%= f.text_field :password, placeholder: "Enter temporary password", label_class: "home-label" %>
          <%= f.button :submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/new.html.erb
<div id="wrapper">
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand"><%= link_to('Admin', admin_index_path) %></li>
      <li><%= link_to('Manage Users', admin_new_path) %></li>
      <li><%= link_to('Manage Products', admin_products_path) %></li>
      <li><%= link_to('Add Product', admin_new_product_path) %></li>
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    </ul>
  </div>
  <div id="page-content-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 well">
          <h4>Selected user: <%= @selected_user.email %></h4>
          <h3>Select a user</h3>
          <%= form_tag admin_new_path, :method => 'get', :id => "users_search" do %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :name => nil %>
          </p>
          <% end %>
          <div id="user-list">
            <%= render :partial => "users" %>
          </div>
        </div>
        <div class="col-sm-5 col-sm-offset-1 well">
          <div id="added-products-list">
            <%= render :partial => "addedproducts" %>
          </div>
        </div>
      </div>
        <div class="row">
          <div class="col-sm-12 special-item-col well">
            <%= form_tag admin_new_path, :method => 'get', :id => "special_search" do %>
            <p>
              Select Items
              <%= text_field_tag :inv_code, params[:inv_code] %>
              <%= submit_tag "Search", :name => nil %>
            </p>
            <% end %>
            <div id="special-list">
              <%= render :partial => "special" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/new.js.erb
$("#special-list").html("<%= escape_javascript( render( :partial => 'special' ))%>");
$("#user-list").html("<%= escape_javascript( render( :partial => 'users' ))%>");

$("#all-products").html("<%= escape_javascript( render( :partial => 'all-products' ))%>");

app/views/admin/new_product.html.erb
<div id="wrapper">
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand"><%= link_to('Admin', admin_index_path) %></li>
      <li><%= link_to('Manage Users', admin_new_path) %></li>
      <li><%= link_to('Manage Products', admin_products_path) %></li>
      <li><%= link_to('Add Product', admin_new_product_path) %></li>
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    </ul>
  </div>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          <h1>Please select what kind of item you are adding</h1>
          <div class="radio-buttons">
            <%= label_tag 'Inventory Product' %>
            <%= radio_button_tag 'product', 'inventory product', :class => "form-control" %>
            <%= label_tag 'Special Product' %>
            <%= radio_button_tag 'product', 'special product', :class => "form-control" %>
          </div>
          <div id="special-product-form">
            <%= bootstrap_form_for @special_product, method: :post, url: admin_create_special_product_path do |f| %>
              <%= f.text_field  :inventory_code %>
              <%= f.text_field :description %>
              <%= f.number_field :stock, value: 1 %>
              <%= f.text_field :product_code %>
              <%= f.submit %>
            <% end %>
          </div>
          <div id="inventory-product-form">
            <%= bootstrap_form_for @inventory_product, method: :post, url: admin_create_inventory_product_path do |f| %>
              <%= f.text_field  :inventory_code %>
              <%= f.text_field :description %>
              <%= f.number_field :stock, value: 1 %>
              <%= f.text_field :product_code %>
              <%= f.submit %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products.html.erb
<div id="wrapper">
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand"><%= link_to('Admin', admin_index_path) %></li>
      <li><%= link_to('Manage Users', admin_new_path) %></li>
      <li><%= link_to('Manage Products', admin_products_path) %></li>
      <li><%= link_to('Add Product', admin_new_product_path) %></li>
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    </ul>
  </div>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          <%= form_tag admin_new_path, :method => 'get', :id => "all_search" do %>
          <p>
            <%= text_field_tag :inv_code, params[:inv_code] %>
            <%= submit_tag "Search", :name => nil %>
          </p>
          <% end %>
          <div id="all-products">
            <%= render :partial => "all-products" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>