config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :order, only: [:index, :update]

  resources :carts, only: [:show]

  resources :order_items, only: [:create, :update, :destroy]

  get '/order/items', to: 'order#items', as: 'all_items'

  get '/admin', to: 'admin#index', as: 'admin_index'

  get '/admin/new', to: 'admin#new', as: 'admin_new'

  get '/admin/products', to: 'admin#products', as: 'admin_products'

  get '/admin/new_product', to: 'admin#new_product', as: 'admin_new_product'

  patch '/admin/update_special/:id', to: 'admin#update_special', as: 'admin_update_special'

  patch '/admin/update_inventory/:id', to: 'admin#update_inventory', as: 'admin_update_inventory'

  delete '/admin/delete_special/:id', to: 'admin#delete_special', as: 'admin_delete_special'

  delete '/admin/delete_inventory/:id', to: 'admin#delete_inventory', as: 'admin_delete_inventory'

  post '/admin/create', to: 'admin#create_product', as: 'admin_create_product'

  post '/admin/create_inventory', to: 'admin#create_inventory_product', as: 'admin_create_inventory_product'

  post '/admin/create_special', to: 'admin#create_special_product', as: 'admin_create_special_product'

  post 'create_user' => 'admin#create', as: :create_user

  post 'selected_user' => 'admin#selected_user', as: :selected_user

  post 'create_product_user' => 'admin#product_user', as: :product_user

  delete 'delete_product_user' => 'admin#delete_product', as: :delete_product

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
    @order = current_order
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_url %>">Mountain View Estates Coffee</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
          <li style="margin-top: 11px;"><a href="/order">Home</a></li>
          <li style="margin-top: 11px;"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          <li><a href="/carts/1">Shopping cart total <%= current_order.order_items.length %> view cart: <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/carts/show.html.erb
<%= render partial: 'navbar' %>
<div class="container">
  <div class="row row-cart">
    <div class="col-xs-12">
      <% if !@order_item.nil? && @order_item.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @order_item.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <% if @order_items.size == 0 %>
        <h2>
          There are no items in your shopping cart. Please <%= link_to "go back", order_index_path %> and add items to cart
        </h2>
      <% else %>
      <h1>Current Cart: </h1>
      <table class="table">

        <% @order_items.each do |order_item| %>
         <tr>
          <%= bootstrap_form_for(order_item) do |f| %>
            <% if order_item.inventory_product == nil %>
              <th class="product-name"><%= order_item.special_product.description %></th>
              <th><%= f.number_field :quantity, value: order_item.quantity.to_i, min: 0 %></th>
              <th class="products-button"><%= f.button :submit, :class => "btn btn-primary" %></th>
            <% else %>
              <th class="product-name"><%= order_item.inventory_product.description %></th>
              <th><%= f.number_field :quantity, value: order_item.quantity.to_i, min: 0 %></th>
              <th class="products-button"><%= f.button :submit, :class => "btn btn-primary" %></th>
            <% end %>
          <% end %>
        </tr>
        <% end %>
      </table>
        <%= form_for @order, url: order_url {action:"update"} do |f| %>
          <th>Everything look good?</th>
          <%= f.button :submit, :class => "btn btn-primary" %>
        <% end %>
      <% end %>
    </div>

  </div>

</div>